import { LoaderCircle, Plus, Sparkles } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

type AddProductDialogProps = {
  isCreating: boolean;
  onCreate: (payload: { name: string; description: string }) => Promise<void>;
  errorMessage: string | null;
  successMessage: string | null;
};

const AddProductDialog = ({
  isCreating,
  onCreate,
  errorMessage,
  successMessage,
}: AddProductDialogProps) => {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [validationError, setValidationError] = useState<string | null>(null);

  useEffect(() => {
    if (successMessage) {
      setOpen(false);
      setName("");
      setDescription("");
      setValidationError(null);
    }
  }, [successMessage]);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!name.trim() || !description.trim()) {
      setValidationError("Name and description are required.");
      return;
    }

    setValidationError(null);
    await onCreate({ name: name.trim(), description: description.trim() });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button
          type="button"
          className="bg-emerald-700 text-emerald-50 hover:bg-emerald-800"
        >
          <Plus className="size-4" />
          Add Product
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-lg border border-emerald-200/60 bg-white/95 dark:border-emerald-900/40 dark:bg-slate-900">
        <DialogHeader>
          <DialogTitle className="inline-flex items-center gap-2">
            <Sparkles className="size-4 text-emerald-600 dark:text-emerald-300" />
            Create Product
          </DialogTitle>
          <DialogDescription>
            Add product name and description. AI metadata will be generated by
            the backend.
          </DialogDescription>
        </DialogHeader>

        <form className="space-y-4" onSubmit={handleSubmit}>
          <div className="space-y-2">
            <label
              className="text-sm font-medium text-foreground"
              htmlFor="name"
            >
              Product Name
            </label>
            <input
              id="name"
              value={name}
              onChange={(event) => setName(event.target.value)}
              placeholder="Bamboo Toothbrush"
              className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20"
              disabled={isCreating}
            />
          </div>

          <div className="space-y-2">
            <label
              className="text-sm font-medium text-foreground"
              htmlFor="description"
            >
              Description
            </label>
            <textarea
              id="description"
              value={description}
              onChange={(event) => setDescription(event.target.value)}
              placeholder="Eco-friendly biodegradable toothbrush for daily oral care."
              className="min-h-24 w-full rounded-md border border-border bg-background px-3 py-2 text-sm outline-none transition focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20"
              disabled={isCreating}
            />
          </div>

          {validationError ? (
            <p className="rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/30 dark:text-rose-200">
              {validationError}
            </p>
          ) : null}

          {errorMessage ? (
            <p className="rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/30 dark:text-rose-200">
              {errorMessage}
            </p>
          ) : null}

          {successMessage ? (
            <p className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-200">
              {successMessage}
            </p>
          ) : null}

          <DialogFooter className="mx-0 mb-0 border-none bg-transparent px-0 pb-0 pt-2">
            <Button type="submit" disabled={isCreating}>
              {isCreating ? (
                <>
                  <LoaderCircle className="size-4 animate-spin" />
                  Creating...
                </>
              ) : (
                "Create Product"
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default AddProductDialog;
